String literals (used as tfop attrs) are again getting different SIL code pattern, causing the infamous /usr/local/google/home/hongm/ssd_part/git/swift-tensorflow-merge/swift/test/TensorFlowRuntime/tensor.swift:263:13: error: attribute 'padding' requires a constant argument   let y = x.convolved2D(withFilter: filter, strides: (1, 1, 1, 1),
Filed https://bugs.swift.org/browse/SR-8117 for it, which should go away once we
move the partition pass to be right after deabstraction.

The short-term fix here is to avoid using small strings, so that compiler
will *not* generate the _StringObject.init(_smallUTF8SecondWord:) call.

Also tried an alternative suggested by rxwei@, where we pad the string literal
at the end of deabstraction pass, and remove the padding when lowering the insts
to TF ops. Unfortunately it did not work out -- for device string literals, even
after we pad with 16+ bytes (e.g. pad "/device:CPU:0" into
"________________/device:CPU:0"), _StringObject.init(_smallUTF8SecondWord:) is
still generated somehow.

Also renamed the device pseudo-attr from "device" to "__device", for consistency
with "__shapes".

The only compiler test failure is now TensorFlow/tensor_autodiff.swift.